In [1]:
import os
import pandas as pd
import numpy as np
import gmplot
from pathlib import Path

## Choose working directory:

In [2]:
os.chdir('F:\hackathon_4.4.20')

In [3]:
os.getcwd()

'F:\\hackathon_4.4.20'

In [4]:
os.listdir()

['my_heatmap.html',
 'my_heatmap_1.html',
 'my_heatmap_2.html',
 'my_heatmap_3.html',
 'my_heatmap_cough_filtered.html',
 'my_heatmap_fever_filtered.html',
 'my_heatmap_unfiltered.html',
 'my_map.html',
 'postal_code_coordinates.csv',
 'random_data.csv',
 'symptoms_table.csv',
 'user001_clus_time.html']

## Load data:

In [5]:
symptoms_table = pd.read_csv('Random_Data.csv', sep=';')
symptoms_table.head()

,PLZ,Year,Sex,Timestamp,Fever,Cough,Shortness of Breath,Unnamed: 7,Tiredness,Aches,...,Cough.4,Shortness of Breath.4,Unnamed: 55,Tiredness.4,Aches.4,Runny Nose.4,Sore Throught.4,Diarrhea.4,Loss of Taste.4,Temperature.4
0,1000,1980,f,17.03.2020,0,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,NaN
1,1000,1927,m,17.03.2020,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,NaN
2,1000,1982,f,17.03.2020,0,0,0,1,0,0,...,0,0,0,1,1,0,0,0,0,NaN
3,1000,2004,m,17.03.2020,0,0,1,0,0,0,...,0,1,0,1,0,0,1,0,0,NaN
4,1000,1964,m,17.03.2020,0,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,NaN

In [6]:
print(set(symptoms_table.Timestamp))
print(len(set(symptoms_table.PLZ)))
print(symptoms_table.shape)

{'17.03.2020'}
3218
(100687, 63)

In [7]:
os.getcwd()

'F:\\hackathon_4.4.20'

In [8]:
os.listdir()

['my_heatmap.html',
 'my_heatmap_1.html',
 'my_heatmap_2.html',
 'my_heatmap_3.html',
 'my_heatmap_cough_filtered.html',
 'my_heatmap_fever_filtered.html',
 'my_heatmap_unfiltered.html',
 'my_map.html',
 'postal_code_coordinates.csv',
 'random_data.csv',
 'symptoms_table.csv',
 'user001_clus_time.html']

In [9]:
import csv

## Load the postal-code-coordinate-conversion table:

### Postal code - coordinates table downloaded from: https://github.com/gamba/swiss-geolocation/blob/master/post-codes.csv

In [10]:
postal_code_coordinate_conversion = pd.read_csv('postal_code_coordinates.csv', sep=',')
postal_code_coordinate_conversion.head()

,zip,post_district,comment,country_code,region,town,lat,lng
0,1000,Lausanne,NaN,CH,VD,Lausanne,46.567488,6.680964
1,1001,Lausanne 1 cases,PO box only,CH,VD,Lausanne,46.243526,7.382073
2,1002,Lausanne,PO box only,CH,VD,Lausanne,46.521820,6.632665
3,1003,Lausanne Secteur de dist.,NaN,CH,VD,Lausanne,46.520793,6.631489
4,1004,Lausanne,NaN,CH,VD,Lausanne,46.530039,6.617949

In [11]:
#set(postal_code_coordinate_conversion.zip)

In [12]:
postal_code_coordinate_conversion

,zip,post_district,comment,country_code,region,town,lat,lng
0,1000,Lausanne,NaN,CH,VD,Lausanne,46.567488,6.680964
1,1001,Lausanne 1 cases,PO box only,CH,VD,Lausanne,46.243526,7.382073
2,1002,Lausanne,PO box only,CH,VD,Lausanne,46.521820,6.632665
3,1003,Lausanne Secteur de dist.,NaN,CH,VD,Lausanne,46.520793,6.631489
4,1004,Lausanne,NaN,CH,VD,Lausanne,46.530039,6.617949
...,...,...,...,...,...,...,...,...
5874,9656,Alt St. Johann,NaN,CH,SG,Alt St. Johann,47.181195,9.276218
5875,9656,Starkenbach,NaN,CH,SG,Alt St. Johann,47.185880,9.249370
5876,9657,Unterwasser,NaN,CH,SG,Unterwasser,47.197165,9.308609
5877,9658,Oberdorf SG,NaN,CH,SG,Wildhaus,47.203334,9.350492
5878,9658,Wildhaus,NaN,CH,SG,Wildhaus,47.203334,9.350492

lat_values = []
lng_values = []

for plz in symptoms_table.PLZ:
    check_bools = postal_code_coordinate_conversion.zip==plz
    #print(postal_code_coordinate_conversion[check_bools])
    lat_value = postal_code_coordinate_conversion[check_bools].lat
    lng_value = postal_code_coordinate_conversion[check_bools].lng
    lat_values.append(lat_value)
    lng_values.append(lng_value)

symptoms_table['latitude'] = lat_values
symptoms_table['longitude'] = lng_values

lat_values_clean = []
for lat_value in lat_values[:5]:
    lat_values_clean.append(lat_value[0])
    print(lat_value[0])
lat_values_clean

## Merge the two tables:

In [13]:
symptoms_table = symptoms_table.join(postal_code_coordinate_conversion.set_index('zip'), on='PLZ')

In [14]:
symptoms_table.head()

,PLZ,Year,Sex,Timestamp,Fever,Cough,Shortness of Breath,Unnamed: 7,Tiredness,Aches,...,Diarrhea.4,Loss of Taste.4,Temperature.4,post_district,comment,country_code,region,town,lat,lng
0,1000,1980,f,17.03.2020,0,0,1,1,0,0,...,0,0,NaN,Lausanne,NaN,CH,VD,Lausanne,46.567488,6.680964
1,1000,1927,m,17.03.2020,0,0,0,0,1,0,...,0,0,NaN,Lausanne,NaN,CH,VD,Lausanne,46.567488,6.680964
2,1000,1982,f,17.03.2020,0,0,0,1,0,0,...,0,0,NaN,Lausanne,NaN,CH,VD,Lausanne,46.567488,6.680964
3,1000,2004,m,17.03.2020,0,0,1,0,0,0,...,0,0,NaN,Lausanne,NaN,CH,VD,Lausanne,46.567488,6.680964
4,1000,1964,m,17.03.2020,0,0,1,0,0,0,...,0,0,NaN,Lausanne,NaN,CH,VD,Lausanne,46.567488,6.680964

In [15]:
latitudes = list(symptoms_table['lat'])
longitudes = list(symptoms_table['lng'])
#latitudes_nice = np.concatenate(symptoms_table['latitude']).tolist()
#longitudes_nice = np.concatenate(symptoms_table['latitude']).tolist()

In [16]:
symptoms_table.head()

,PLZ,Year,Sex,Timestamp,Fever,Cough,Shortness of Breath,Unnamed: 7,Tiredness,Aches,...,Diarrhea.4,Loss of Taste.4,Temperature.4,post_district,comment,country_code,region,town,lat,lng
0,1000,1980,f,17.03.2020,0,0,1,1,0,0,...,0,0,NaN,Lausanne,NaN,CH,VD,Lausanne,46.567488,6.680964
1,1000,1927,m,17.03.2020,0,0,0,0,1,0,...,0,0,NaN,Lausanne,NaN,CH,VD,Lausanne,46.567488,6.680964
2,1000,1982,f,17.03.2020,0,0,0,1,0,0,...,0,0,NaN,Lausanne,NaN,CH,VD,Lausanne,46.567488,6.680964
3,1000,2004,m,17.03.2020,0,0,1,0,0,0,...,0,0,NaN,Lausanne,NaN,CH,VD,Lausanne,46.567488,6.680964
4,1000,1964,m,17.03.2020,0,0,1,0,0,0,...,0,0,NaN,Lausanne,NaN,CH,VD,Lausanne,46.567488,6.680964

In [17]:
symptoms_table

,PLZ,Year,Sex,Timestamp,Fever,Cough,Shortness of Breath,Unnamed: 7,Tiredness,Aches,...,Diarrhea.4,Loss of Taste.4,Temperature.4,post_district,comment,country_code,region,town,lat,lng
0,1000,1980,f,17.03.2020,0,0,1,1,0,0,...,0,0,NaN,Lausanne,NaN,CH,VD,Lausanne,46.567488,6.680964
1,1000,1927,m,17.03.2020,0,0,0,0,1,0,...,0,0,NaN,Lausanne,NaN,CH,VD,Lausanne,46.567488,6.680964
2,1000,1982,f,17.03.2020,0,0,0,1,0,0,...,0,0,NaN,Lausanne,NaN,CH,VD,Lausanne,46.567488,6.680964
3,1000,2004,m,17.03.2020,0,0,1,0,0,0,...,0,0,NaN,Lausanne,NaN,CH,VD,Lausanne,46.567488,6.680964
4,1000,1964,m,17.03.2020,0,0,1,0,0,0,...,0,0,NaN,Lausanne,NaN,CH,VD,Lausanne,46.567488,6.680964
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100684,9658,1932,f,17.03.2020,1,0,0,1,0,0,...,0,0,NaN,Wildhaus,NaN,CH,SG,Wildhaus,47.203334,9.350492
100685,9658,1943,m,17.03.2020,0,0,0,0,0,0,...,0,0,NaN,Oberdorf SG,NaN,CH,SG,Wildhaus,47.203334,9.350492
100685,9658,1943,m,17.03.2020,0,0,0,0,0,0,...,0,0,NaN,Wildhaus,NaN,CH,SG,Wildhaus,47.203334,9.350492
100686,9658,1988,m,17.03.2020,0,1,0,0,0,0,...,0,0,NaN,Oberdorf SG,NaN,CH,SG,Wildhaus,47.203334,9.350492
100686,9658,1988,m,17.03.2020,0,1,0,0,0,0,...,0,0,NaN,Wildhaus,NaN,CH,SG,Wildhaus,47.203334,9.350492

## Save the dataframe as csv file:

In [18]:
path_to_files = Path('F:\hackathon_4.4.20\symptoms_table.csv')

In [19]:
symptoms_table.to_csv(path_to_files, sep=';')

latitudes = symptoms_table['lat'][:15000] 
longitudes = symptoms_table['lng'][:15000]
fever = symptoms_table['Fever'][:15000]

# Store our latitude and longitude


# Creating the location we would like to initialize the focus on. 
# Parameters: Lattitude, Longitude, Zoom
gmap = gmplot.GoogleMapPlotter(latitudes[0], longitudes[0], 10)

# Overlay our datapoints onto the map
gmap.heatmap(latitudes, longitudes)
#gmplot.heatmap_weighted(latitudes, longitudes, fever)

# Generate the heatmap into an HTML file
gmap.draw("my_heatmap.html")

## Create a diluted version of the data frame (fewer data points per postal code):

In [20]:
possible_postal_codes = list(set(symptoms_table.PLZ))

In [21]:
symptoms_tables_by_plz = {}
for postal_code in possible_postal_codes:
    symptoms_tables_by_plz[postal_code] = symptoms_table[symptoms_table.PLZ==postal_code]

In [22]:
symptoms_tables_by_plz[possible_postal_codes[0]]

,PLZ,Year,Sex,Timestamp,Fever,Cough,Shortness of Breath,Unnamed: 7,Tiredness,Aches,...,Diarrhea.4,Loss of Taste.4,Temperature.4,post_district,comment,country_code,region,town,lat,lng
82078,8192,1929,m,17.03.2020,0,0,0,1,1,0,...,0,0,NaN,Glattfelden,NaN,CH,ZH,Glattfelden,47.559858,8.499377
82078,8192,1929,m,17.03.2020,0,0,0,1,1,0,...,0,0,NaN,Zweidlen,NaN,CH,ZH,Zweidlen,47.560800,8.467370
82079,8192,1977,m,17.03.2020,1,0,0,0,0,0,...,0,0,NaN,Glattfelden,NaN,CH,ZH,Glattfelden,47.559858,8.499377
82079,8192,1977,m,17.03.2020,1,0,0,0,0,0,...,0,0,NaN,Zweidlen,NaN,CH,ZH,Zweidlen,47.560800,8.467370
82080,8192,1925,f,17.03.2020,0,0,0,0,0,0,...,0,0,NaN,Glattfelden,NaN,CH,ZH,Glattfelden,47.559858,8.499377
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82130,8192,1965,m,17.03.2020,0,0,0,0,0,0,...,0,0,NaN,Zweidlen,NaN,CH,ZH,Zweidlen,47.560800,8.467370
82131,8192,2005,m,17.03.2020,0,0,1,0,0,0,...,0,0,NaN,Glattfelden,NaN,CH,ZH,Glattfelden,47.559858,8.499377
82131,8192,2005,m,17.03.2020,0,0,1,0,0,0,...,0,0,NaN,Zweidlen,NaN,CH,ZH,Zweidlen,47.560800,8.467370
82132,8192,1945,m,17.03.2020,0,0,0,0,1,0,...,0,0,NaN,Glattfelden,NaN,CH,ZH,Glattfelden,47.559858,8.499377
82132,8192,1945,m,17.03.2020,0,0,0,0,1,0,...,0,0,NaN,Zweidlen,NaN,CH,ZH,Zweidlen,47.560800,8.467370

In [23]:
len(symptoms_tables_by_plz)

3218

In [24]:
symptoms_tables_by_plz_half = {}
for plz, data in symptoms_tables_by_plz.items():
    num_rows = data.shape[0]
    num_rows_half = round(num_rows/2)
    symptoms_tables_by_plz_half[plz] = data.iloc[:num_rows_half,:]

In [25]:
symptoms_tables_by_plz_half[8192].shape

(55, 70)

## Take the first 1500 data points of the data frame:

In [26]:
symptoms_table_light = pd.concat(symptoms_tables_by_plz_half)
symptoms_table_light = symptoms_table_light.iloc[:1500,:]

In [27]:
symptoms_table_light.head()

             PLZ  Year Sex   Timestamp  Fever  Cough  Shortness of Breath  \
8192 82078  8192  1929   m  17.03.2020      0      0                    0
     82078  8192  1929   m  17.03.2020      0      0                    0
     82079  8192  1977   m  17.03.2020      1      0                    0
     82079  8192  1977   m  17.03.2020      1      0                    0
     82080  8192  1925   f  17.03.2020      0      0                    0

            Unnamed: 7  Tiredness  Aches  ...  Diarrhea.4  Loss of Taste.4  \
8192 82078           1          1      0  ...           0                0
     82078           1          1      0  ...           0                0
     82079           0          0      0  ...           0                0
     82079           0          0      0  ...           0                0
     82080           0          0      0  ...           0                0

            Temperature.4  post_district  comment country_code  region  \
8192 82078            NaN    Glattfelden      NaN           CH      ZH
     82078            NaN       Zweidlen      NaN           CH      ZH
     82079            NaN    Glattfelden      NaN           CH      ZH
     82079            NaN       Zweidlen      NaN           CH      ZH
     82080            NaN    Glattfelden      NaN           CH      ZH

                   town        lat       lng
8192 82078  Glattfelden  47.559858  8.499377
     82078     Zweidlen  47.560800  8.467370
     82079  Glattfelden  47.559858  8.499377
     82079     Zweidlen  47.560800  8.467370
     82080  Glattfelden  47.559858  8.499377

[5 rows x 70 columns]

In [28]:
symptoms_table_light.shape

(1500, 70)

##  Create an unfiltered heat-map (the map will simply reflect the density of people who provided information):

In [29]:
latitudes = symptoms_table_light['lat']
longitudes = symptoms_table_light['lng']

In [30]:
# Store our latitude and longitude


# Creating the location we would like to initialize the focus on. 
# Parameters: Lattitude, Longitude, Zoom
gmap = gmplot.GoogleMapPlotter(latitudes[0], longitudes[0], 10)

# Overlay our datapoints onto the map
gmap.heatmap(latitudes, longitudes)
#gmplot.heatmap_weighted(latitudes, longitudes, fever)

# Generate the heatmap into an HTML file
gmap.draw("my_heatmap_unfiltered.html")

## Create a heat-map showing the density of people with fever:

In [31]:
set(symptoms_table_light.Fever)

{0, 1}

In [32]:
fever_filter = 1
symptoms_fever_filtered = symptoms_table_light[symptoms_table_light.Fever==fever_filter]

In [33]:
latitudes = symptoms_fever_filtered['lat']
longitudes = symptoms_fever_filtered['lng']

In [34]:
# Parameters: Lattitude, Longitude, Zoom
gmap = gmplot.GoogleMapPlotter(latitudes[0], longitudes[0], 10)

# Overlay our datapoints onto the map
gmap.heatmap(latitudes, longitudes)

# Generate the heatmap into an HTML file
gmap.draw("my_heatmap_fever_filtered.html")

In [35]:
symptoms_fever_filtered.shape

(110, 70)

## Create a heat-map showing the density of people who cough:

In [36]:
set(symptoms_table_light.Cough)

{0, 1}

In [37]:
cough_filter = 1
symptoms_filtered = symptoms_table_light[symptoms_table_light.Cough==cough_filter]

In [38]:
latitudes = symptoms_filtered['lat']
longitudes = symptoms_filtered['lng']

In [39]:
# Parameters: Lattitude, Longitude, Zoom
gmap = gmplot.GoogleMapPlotter(latitudes[0], longitudes[0], 10)

# Overlay our datapoints onto the map
gmap.heatmap(latitudes, longitudes)

# Generate the heatmap into an HTML file
gmap.draw("my_heatmap_cough_filtered.html")